import Link from "next/link";
import { SiteFooter, SiteNav } from "@/app/components/SiteChrome";
import TrackedLink from "@/app/components/TrackedLink";
import GuideWorksheetExample from "@/app/components/GuideWorksheetExample";
export const metadata = { title: "Amount Financed vs. Total of Payments | PencilProof", description: "Understand the difference between amount financed and total of payments on a car loan using a clear educational estimate.", alternates: { canonical: "/guides/amount-financed-vs-total-of-payments" } };
export default function AmountVsTotalGuide() { const jsonLd = { "@context":"https://schema.org", "@type":"Article", headline:"Amount Financed vs. Total of Payments: What Will You Really Repay?", description:String(metadata.description), url:"https://pencilproof.com/guides/amount-financed-vs-total-of-payments", publisher:{"@type":"Organization",name:"PencilProof"} }; return <main><SiteNav /><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
<section className="page-hero shell"><div className="page-hero-copy"><p className="kicker">CONTRACT CLARITY GUIDE</p><h1>Amount financed vs. total of payments: what will you really repay?</h1><p>Amount financed is the balance borrowed. Total of payments is the sum of scheduled payments. They answer different questions on a written car contract.</p><div className="page-actions"><TrackedLink analyticsCategory="guide_amount_vs_total" className="button button-primary" href="/analyze">Review your quote free <span aria-hidden="true">→</span></TrackedLink><Link className="text-link" href="/guides/reading-car-dealer-worksheet">Read the worksheet guide <span aria-hidden="true">→</span></Link></div></div></section>
<section className="section shell checks-grid-section" aria-labelledby="terms"><div className="section-intro compact"><p className="kicker">READ BOTH LINES</p><h2 id="terms">Borrowed balance and scheduled repayment are not the same.</h2><p>Use the written contract, not a payment estimate alone. Figures below are fictional educational estimates, not a lender offer or financial advice.</p></div><div className="check-list"><article><b>Amount financed</b><p>The principal balance used to calculate the installment schedule.</p></article><article><b>Finance charge</b><p>The estimated borrowing cost shown separately on the contract.</p></article><article><b>Total of payments</b><p>The scheduled payment multiplied by the number of payments.</p></article><article><b>Check the inputs</b><p>Verify APR, term, price, fees, products, trade figures, and cash down.</p></article></div></section>
<GuideWorksheetExample title="Illustrative $30,000 loan at 7.50% APR" explanation="A standard monthly installment estimate shows how scheduled payments add borrowing cost. Actual contract figures control." lines={[{label:"Amount financed",value:"$30,000"},{label:"Term",value:"60 months"},{label:"Estimated payment",value:"about $601.14/mo"},{label:"Estimated total of payments",value:"$36,068.31"},{label:"Estimated finance charge",value:"$6,068.31",emphasis:true}]} question="Where are amount financed, finance charge, and total of payments shown on this written contract?" />
<section className="section route-guide-section"><div className="shell section-intro compact"><p className="kicker">MAKE IT SPECIFIC</p><h2>Check the written numbers before you sign.</h2><p>Upload a PDF or image for free, review detected figures, and ask focused questions about the balance and repayment schedule.</p><TrackedLink analyticsCategory="guide_amount_vs_total_bottom" className="button button-primary" href="/analyze">Start the free scan <span aria-hidden="true">→</span></TrackedLink></div></section><SiteFooter /></main>; }
